"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision if down_revision else "none (first revision)"}
Create Date: ${create_date}
"""

<%doc>
    sa and op are imported only when the operations use them, so an empty revision (plain or
    autogenerated with no changes) passes ruff's unused-import check.
</%doc>
<% operations = (upgrades or "") + (downgrades or "") %>
from collections.abc import Sequence
% if "sa." in operations or "op." in operations:

% endif
% if "sa." in operations:
import sqlalchemy as sa
% endif
% if "op." in operations:
from alembic import op
% endif
${imports if imports else ""}
revision: str = ${repr(up_revision)}
down_revision: str | Sequence[str] | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
