from pathlib import Path

from alembic.command import check, downgrade, upgrade
from alembic.config import Config
from sqlalchemy import create_engine, inspect

ALEMBIC_INI = Path(__file__).resolve().parents[2] / "alembic.ini"


def _config(db_path: Path) -> Config:
    """Alembic config for the storage package, pointed at a throwaway SQLite file."""
    config = Config(str(ALEMBIC_INI))
    config.set_main_option("sqlalchemy.url", f"sqlite:///{db_path}")
    return config


def _table_names(db_path: Path) -> set[str]:
    engine = create_engine(f"sqlite:///{db_path}")
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_upgrades_to_head_and_downgrades_to_base_when_baseline_is_empty(tmp_path: Path) -> None:
    db_path = tmp_path / "agent-hub.db"
    config = _config(db_path)

    upgrade(config, "head")
    assert _table_names(db_path) == {"alembic_version"}

    downgrade(config, "base")
    assert _table_names(db_path) == {"alembic_version"}


def test_reports_no_pending_changes_when_database_at_head(tmp_path: Path) -> None:
    config = _config(tmp_path / "agent-hub.db")
    upgrade(config, "head")

    check(config)  # raises AutogenerateDiffsDetected when metadata and migrations drift
