import io
import runpy
import sys
from pathlib import Path

import pytest
from alembic.command import check, downgrade, upgrade
from alembic.runtime.migration import MigrationContext
from sqlalchemy import create_engine, inspect

from agent_hub.storage.migration import alembic_config


def _table_names(db_path: Path) -> set[str]:
    engine = create_engine(f"sqlite:///{db_path}")
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def _current_revision(db_path: Path) -> str | None:
    """The revision stamped in ``alembic_version``; the table also exists (empty) at base."""
    engine = create_engine(f"sqlite:///{db_path}")
    try:
        with engine.connect() as connection:
            return MigrationContext.configure(connection).get_current_revision()
    finally:
        engine.dispose()


def test_upgrades_to_head_and_downgrades_to_base_when_baseline_is_empty(tmp_path: Path) -> None:
    db_path = tmp_path / "agent-hub.db"
    config = alembic_config(f"sqlite:///{db_path}")

    upgrade(config, "head")
    assert _current_revision(db_path) == "0001"
    assert _table_names(db_path) == {"alembic_version"}

    downgrade(config, "base")
    assert _current_revision(db_path) is None
    assert _table_names(db_path) == {"alembic_version"}


def test_reports_no_pending_changes_when_database_at_head(tmp_path: Path) -> None:
    config = alembic_config(f"sqlite:///{tmp_path / 'agent-hub.db'}")
    upgrade(config, "head")

    check(config)  # raises AutogenerateDiffsDetected when metadata and migrations drift


def test_emits_sql_when_upgrade_runs_offline(tmp_path: Path) -> None:
    db_path = tmp_path / "agent-hub.db"
    config = alembic_config(f"sqlite:///{db_path}")
    # Config binds its default stdout at import time, so capsys would not see the SQL.
    config.output_buffer = io.StringIO()

    upgrade(config, "head", sql=True)

    assert "alembic_version" in config.output_buffer.getvalue()
    assert not db_path.exists()


def test_upgrades_to_head_when_run_as_module(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    db_path = tmp_path / "agent-hub.db"
    argv = ["agent_hub.storage.migration", "-x", f"db_url=sqlite:///{db_path}", "upgrade", "head"]
    monkeypatch.setattr(sys, "argv", argv)
    # Run it the way `python -m` does: a fresh module, not the copy this test file imported.
    monkeypatch.delitem(sys.modules, "agent_hub.storage.migration")

    runpy.run_module("agent_hub.storage.migration", run_name="__main__")

    assert _current_revision(db_path) == "0001"
